import Navbar from "../components/Navbar";
import Sidebar from "../components/Sidebar";

import "./globals.css";
import { Inter } from "next/font/google";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const Layout = ({ children }) => {
  return (
    <html lang="en">
      <body>
        <Navbar />
        
        {children}
        


      </body>
    </html>
  );
};

export default Layout;
